const button = document.querySelector('.menu-button');
const nav = document.querySelector('.nav');
const replay = document.querySelector('.play-button');
const furniture = document.querySelectorAll('.furniture');
if (button && nav) { button.addEventListener('click', () => { const open = nav.classList.toggle('open'); button.setAttribute('aria-expanded', String(open)); button.textContent = open ? 'CLOSE −' : 'MENU +'; }); nav.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { nav.classList.remove('open'); button.setAttribute('aria-expanded', 'false'); button.textContent = 'MENU +'; })); }
if (replay) replay.addEventListener('click', () => { furniture.forEach((piece) => { piece.style.animation = 'none'; void piece.offsetWidth; piece.style.animation = ''; }); });
const formatPrice = (price) => new Intl.NumberFormat('ko-KR').format(price) + '원';
function productCard(product, index) { const card = document.createElement('article'); card.className = 'item-card product-card'; const number = document.createElement('div'); number.className = 'item-number'; number.textContent = String(index + 1).padStart(2, '0'); const imageBox = document.createElement('div'); imageBox.className = 'item-drawing product-image'; const image = document.createElement('img'); image.src = product.image; image.alt = product.name; image.loading = 'lazy'; image.style.cssText = 'display:block;width:100%;height:100%;object-fit:contain;mix-blend-mode:multiply'; imageBox.append(image); const title = document.createElement('div'); title.className = 'item-title'; const label = document.createElement('p'); label.textContent = '직접 구매한 물건'; const heading = document.createElement('h3'); heading.textContent = product.name; title.append(label, heading); const details = document.createElement('dl'); const priceRow = document.createElement('div'); const priceLabel = document.createElement('dt'); priceLabel.textContent = '가격'; const price = document.createElement('dd'); price.textContent = formatPrice(product.price); priceRow.append(priceLabel, price); const sourceRow = document.createElement('div'); const sourceLabel = document.createElement('dt'); sourceLabel.textContent = '출처'; const source = document.createElement('dd'); source.textContent = product.source || '스마트스토어'; sourceRow.append(sourceLabel, source); details.append(priceRow, sourceRow); const buy = document.createElement('a'); buy.className = 'buy-button'; buy.href = product.url; buy.target = '_blank'; buy.rel = 'noopener noreferrer'; buy.textContent = '구매하기 ↗'; card.append(number, imageBox, title, details, buy); return card; }
async function renderProducts() { const homeList = document.querySelector('[data-home-products]') || document.querySelector('.items .item-list'); const productList = document.querySelector('[data-products-list]'); if (!homeList && !productList) return; try { const response = await fetch('products.json'); if (!response.ok) throw new Error('제품 데이터를 불러오지 못했습니다.'); const data = await response.json(); const products = Array.isArray(data.products) ? data.products : []; const render = (target, list) => target.replaceChildren(...list.map(productCard)); if (homeList) render(homeList, products.slice(0, 3)); if (productList) render(productList, products); } catch (error) { [homeList, productList].filter(Boolean).forEach((target) => { target.textContent = '제품 목록을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.'; }); } }
document.querySelectorAll('.nav a[href="#items"], .nav a[href="index.html#items"]').forEach((link) => { link.href = 'products.html'; });
renderProducts();
