(function () {
  var list = document.querySelector('[data-story-list]');
  var main = document.querySelector('.post-wrap');
  function el(tag, className, text) { var node = document.createElement(tag); if (className) node.className = className; if (text != null) node.textContent = text; return node; }
  function dateText(value) { var date = new Date(value + 'T00:00:00'); return isNaN(date) ? value : date.getFullYear() + '. ' + String(date.getMonth() + 1).padStart(2, '0') + '. ' + String(date.getDate()).padStart(2, '0'); }
  function href(post) { return post.url || 'post.html?id=' + encodeURIComponent(post.id || ''); }
  function tags(post) { var box = el('div', 'tags'); (post.tags || []).forEach(function (tag) { box.append(el('span', 'tag', tag)); }); return box; }
  function renderList(posts) { if (!list) return; list.replaceChildren(); if (!posts.length) { list.textContent = '아직 올라온 글이 없습니다.'; return; } posts.forEach(function (post) { var item = el('li', 'blog-card'); var link = el('a'); link.href = href(post); var time = el('time', null, dateText(post.date)); time.dateTime = post.date || ''; link.append(time, el('h2', null, post.title || '제목 없음')); if (post.summary) link.append(el('p', 'summary', post.summary)); if (post.tags && post.tags.length) link.append(tags(post)); item.append(link); list.append(item); }); }
  function bodyBlocks(body) { var box = el('div', 'post-body'); String(body || '').replace(/\r\n/g, '\n').split(/\n\s*\n/).forEach(function (block) { block = block.trim(); if (!block) return; var lines = block.split('\n'); if (lines.every(function (line) { return /^- /.test(line.trim()); })) { var ul = el('ul'); lines.forEach(function (line) { ul.append(el('li', null, line.trim().slice(2))); }); box.append(ul); } else if (/^## /.test(block)) { box.append(el('h2', null, block.slice(3).trim())); } else { box.append(el('p', null, block)); } }); return box; }
  function renderPost(posts) { if (!main) return; var id = new URLSearchParams(location.search).get('id'); var post = posts.find(function (item) { return String(item.id) === id; }); main.replaceChildren(); if (!post) { main.append(el('div', 'not-found', '글을 찾을 수 없습니다.')); return; } document.title = post.title + ' | B01호'; var back = el('a', 'back-link', '← 이야기 목록'); back.href = 'index.html'; var article = el('article'); var head = el('header', 'post-head'); var time = el('time', null, dateText(post.date)); time.dateTime = post.date || ''; head.append(time, el('h1', null, post.title || '제목 없음')); if (post.author) head.append(el('p', 'post-author', post.author)); if (post.tags && post.tags.length) head.append(tags(post)); article.append(head, el('hr', 'post-rule'), bodyBlocks(post.body)); if (Array.isArray(post.faq) && post.faq.length) { var faq = el('section', 'faq'); faq.append(el('h2', null, '자주 묻는 질문')); post.faq.forEach(function (item) { var details = el('details'); details.append(el('summary', null, item.q), el('p', null, item.a)); faq.append(details); }); article.append(faq); } main.append(back, article); }
  function renderRelated(posts) { if (!main) return; var id = new URLSearchParams(location.search).get('id'); var post = posts.find(function (item) { return String(item.id) === id; }); if (!post || !post.relatedProduct || !post.relatedProduct.url) return; var article = main.querySelector('article'); if (!article) return; var link = el('a', 'back-link', String(post.relatedProduct.label || '관련 제품 보기') + ' →'); link.href = String(post.relatedProduct.url); article.append(link); }
  fetch('posts.json', { cache: 'no-store' }).then(function (response) { if (!response.ok) throw new Error(response.status); return response.json(); }).then(function (posts) { posts = Array.isArray(posts) ? posts.slice().sort(function (a, b) { return String(b.date || '').localeCompare(String(a.date || '')); }) : []; renderList(posts); renderPost(posts); renderRelated(posts); }).catch(function () { if (list) list.textContent = '글 목록을 불러오지 못했습니다. 잠시 후 새로고침해 주세요.'; if (main) main.textContent = '글을 불러오지 못했습니다. 잠시 후 새로고침해 주세요.'; });
}());
